import { Metadata } from "next";
import PasswordGenerator from "@/components/tools/PasswordGenerator";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Secure Password Generator | StudentDev Hub",
  description: "Create strong, secure, random passwords instantly to protect your academic accounts.",
};

export default function PasswordGeneratorPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-8 text-center">
        <Link href="/tools" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary transition-colors mb-4">
          <ArrowLeft className="w-4 h-4 mr-1" /> Back to Tools
        </Link>
        <h1 className="text-4xl font-bold mb-4">Secure Password Generator</h1>
        <p className="text-lg text-muted-foreground">Generate random, secure passwords to keep your university accounts and personal data safe.</p>
      </div>

      <div className="mb-16">
        <PasswordGenerator />
      </div>

      <article className="prose prose-invert max-w-none text-muted-foreground border-t border-border pt-12">
        <h2 className="text-3xl font-semibold text-foreground mb-4">The Complete Guide to Password Security and Digital Hygiene</h2>
        <p className="mb-4">
          In our deeply interconnected digital era, students and professionals manage an overwhelming number of online accounts: university portals, student email, mobile banking apps, social media profiles, and obscure SaaS platforms. Relying on simple, easily memorized, and continuously reused passwords makes you highly susceptible to devastating cyberattacks like credential stuffing and data breaches. 
        </p>
        <p className="mb-4">
          A secure, randomly generated character string serves as your absolute first line of defense against unauthorized account access, identity theft, and malicious financial hijacking. Using our random password generator tool above ensures you are instantly producing impenetrable, cryptographic-quality passwords without exerting any mental effort.
        </p>

        <h3 className="text-2xl font-medium text-foreground mt-8 mb-3">The Anatomy of an Uncrackable Password</h3>
        <p className="mb-4">
          When security professionals describe a "strong" password, they strictly refer to passwords that cannot be compromised via automated brute-force scripts within a human lifespan. Achieving this level of security requires adhering to three fundamental principles:
        </p>
        <ul className="list-disc pl-6 space-y-4 mb-6">
          <li>
            <strong className="text-foreground">Sufficient Length (MANDATORY):</strong> Length is the single most critical factor in cryptography. A password should never be shorter than 12 characters. An increase from 8 characters to 16 characters doesn't just double the time it takes to crack—it increases the required time exponentially by trillions of years.
          </li>
          <li>
            <strong className="text-foreground">Randomized Complexity:</strong> A secure password must weave together upper-case letters, lower-case letters, numbers, and special symbols (like $, %, #, and ^). This massively expands the pool of potential characters an automated script must iterate through.
          </li>
          <li>
            <strong className="text-foreground">Zero Predictability:</strong> Dictionary words, birth dates, pet names, and predictable keyboard walks (like "qwerty" or "123456") are breached instantly. Hackers utilize massive "dictionary lists" of billions of known combinations before they even try brute-forcing random characters.
          </li>
        </ul>

        <h3 className="text-2xl font-medium text-foreground mt-8 mb-3">Understanding the Hacker's Arsenal: Brute-Force vs. Credential Stuffing</h3>
        <p className="mb-4">
          How do passwords actually get hacked? Rarely is an international hacker manually sitting at a keyboard guessing your dog's name. They utilize sophisticated, automated software arrays:
        </p>
        <ul className="list-disc pl-6 space-y-4 mb-6">
          <li><strong>Brute-Force Attacks:</strong> This involves botnets throwing millions of random character combinations at a login screen per second until one works. A 16-character pseudo-random password generated by our tool completely defeats brute-force attacks purely through the laws of mathematics.</li>
          <li><strong>Credential Stuffing:</strong> The most common path to a hacked account. If you use the identical password for your Spotify account as your Banking app, and Spotify suffers a data breach, hackers will immediately purchase that leaked credentials list on the dark web. They then write scripts to automatically test your compromised email and password combination against every major banking, social media, and university portal on the web. <strong>This is why password reuse is a fatal security flaw.</strong></li>
        </ul>

        <h3 className="text-2xl font-medium text-foreground mt-8 mb-3">Best Practices: Surviving Password Fatigue with Password Managers</h3>
        <p className="mb-4">
          The obvious problem with generating forty distinct 18-character strings of gibberish is that the human brain lacks the structural capacity to memorize them. This phenomenon leads to "password fatigue," causing users to revert back to lazy security practices.
        </p>
        <p className="mb-4">
          The industry-standard solution is utilizing a <strong>Password Manager</strong> (like Bitwarden, 1Password, or Apple Keychain). These sophisticated applications act as a heavily encrypted vault for your digital life. You generate a completely random password here, paste it into your vault, and let the software auto-fill it for you forevermore. You only ever need to memorize one exceptionally long, complex "Master Password" to unlock the vault.
        </p>
        
        <div className="bg-primary/10 p-6 rounded-xl border border-primary/20 mt-8 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-1 h-full bg-primary"></div>
          <h4 className="text-foreground text-lg font-semibold mb-2">Cryptographic Trivia: The Math of Security</h4>
          <p className="text-sm leading-relaxed">
            A standard 8-character password using only lowercase letters can be brute-forced cracked by a modern consumer-grade GPU array in literally <strong>less than half a second</strong>. <br/><br/>
            Conversely, a 16-character complex password containing letters, numbers, and symbols—like those generated by our tool above—offers so many quintillions of possible mathematical combinations that tracking it would require billions of years of uninterrupted computing time, vastly exceeding the current estimated age of the observable universe.
          </p>
        </div>
      </article>
    </div>
  );
}
