import { Metadata } from "next";
import QuizComponent, { Question } from "@/components/quiz/QuizComponent";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "DBMS Quiz | StudentDev Hub",
  description: "Check your knowledge of database normalization, SQL queries, and ACID properties.",
};

const questions: Question[] = [
  {
    question: "What does the ACID acronym stand for in database transactions?",
    options: ["Atomicity, Consistency, Isolation, Durability", "Action, Commit, Isolation, Data", "Automated, Consistent, Immediate, Durable", "Atomic, Calculated, Isolated, Dependent"],
    answer: 0,
    explanation: "ACID properties (Atomicity, Consistency, Isolation, Durability) ensure that database transactions are processed reliably."
  },
  {
    question: "Which normal form deals with the elimination of partial dependencies?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    answer: 1,
    explanation: "Second Normal Form (2NF) ensures that all non-key attributes are fully functionally dependent on the entire primary key, eliminating partial dependencies."
  },
  {
    question: "Which of the following is a Data Definition Language (DDL) command?",
    options: ["SELECT", "INSERT", "CREATE", "UPDATE"],
    answer: 2,
    explanation: "CREATE is a DDL command used to create database tables or schemas. The others are Data Manipulation Language (DML) or Query operations."
  },
  {
    question: "What is a Foreign Key?",
    options: ["A key that uniquely identifies a record in the current table.", "A key used to establish a relationship to the primary key of another table.", "A key generated by the database automatically.", "A secondary index used for fast searching."],
    answer: 1,
    explanation: "A Foreign Key is an attribute or set of attributes in one table that refers to the primary key in another table, establishing a link between the two tables."
  },
  {
    question: "Which JOIN returns only the rows that have matching values in both tables?",
    options: ["LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN", "INNER JOIN"],
    answer: 3,
    explanation: "An INNER JOIN evaluates the join condition and strictly returns rows where there is a match in both the left and right tables."
  }
];

export default function DbmsQuiz() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-8 text-center">
        <Link href="/practice" className="inline-flex items-center text-sm text-muted-foreground hover:text-green-500 transition-colors mb-4">
          <ArrowLeft className="w-4 h-4 mr-1" /> Back to Quizzes
        </Link>
        <h1 className="text-4xl font-bold mb-4">Database Management Quiz</h1>
        <p className="text-lg text-muted-foreground">Test your knowledge of SQL, Relational Algebra, and Database design.</p>
      </div>
      <div className="mb-16">
        <QuizComponent questions={questions} title="Database Principles" />
      </div>
    </div>
  );
}
